import { expect, test } from "@playwright/test";
import { mkdirSync } from "node:fs";
import path from "node:path";

test("rider locker previews, persists separate gear, and returns from gameplay", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const out = path.resolve("artifacts/drop-in-forest/yeti", testInfo.project.name);
  mkdirSync(out, { recursive: true });
  await page.goto("/resorts/heavenly/drop-in?engine=v2&gfx=webgl");
  await page.getByRole("button", { name: /Style your rider/ }).click();
  const preview = page.locator('canvas[role="img"]');
  await expect(preview).toHaveAttribute("aria-label", /Yeti wearing alpenglow/);
  await expect(preview).toHaveAttribute("data-preview-ready", "true");
  await expect(page.getByText(/3D preview unavailable/)).toBeHidden();
  await preview.scrollIntoViewIfNeeded();
  await expect.poll(async () => preview.evaluate((canvas: HTMLCanvasElement) => canvas.width)).toBeGreaterThan(200);
  await page.screenshot({ path: path.join(out, "alpenglow.png"), fullPage: true });
  await page.getByRole("button", { name: /^Timberline/ }).click();
  await page.getByRole("button", { name: "Ridgeline", exact: true }).click();
  await page.getByLabel("Rider mode").selectOption("snowboarder");
  await page.getByLabel("Snowboard stance").selectOption("goofy");
  await page.getByRole("button", { name: "Nightfall", exact: true }).click();
  await expect(preview).toHaveAttribute("aria-label", /Yeti wearing timberline, riding nightfall snowboard/);
  await preview.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "timberline.png"), fullPage: true });
  await page.getByRole("button", { name: "Human", exact: true }).click();
  await expect(preview).toHaveAttribute("aria-label", /Human/);
  await page.getByRole("button", { name: "Yeti", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: /Style your rider/ }).click();
  await expect(page.getByRole("button", { name: "Ridgeline", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: /^Timberline/ })).toHaveAttribute("aria-pressed", "true");
  await page.getByLabel("Rider mode").selectOption("snowboarder");
  await expect(page.getByRole("button", { name: "Nightfall", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(preview).toHaveAttribute("aria-label", /Yeti wearing timberline, riding nightfall snowboard/);
  await page.getByRole("button", { name: /start descent/i }).click();
  const running = page.locator('[data-drop-in-state="running"]');
  await expect(running).toHaveAttribute("data-drop-in-character", "yeti", { timeout: 90000 });
  await expect(running).toHaveAttribute("data-drop-in-outfit", "timberline");
  await expect(running).toHaveAttribute("data-drop-in-gear", "nightfall");
  await page.waitForTimeout(1500);
  await page.keyboard.press("p");
  await page.getByRole("button", { name: "Change rider & start a new run" }).click();
  await expect(preview).toBeVisible();
  await expect(preview).toHaveAttribute("data-preview-ready", "true");
  await page.getByRole("button", { name: /^Glacier/ }).click();
  await page.getByRole("button", { name: "Human", exact: true }).click();
  await expect(preview).toHaveAttribute("aria-label", /Human wearing glacier/);
  await preview.scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(out, "glacier-human.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: /start descent/i }).click();
  await expect(running).toHaveAttribute("data-drop-in-character", "human", { timeout: 90000 });
  await expect(running).toHaveAttribute("data-drop-in-outfit", "glacier");
  expect(errors).toEqual([]);
});
