/**
 * lib/game/server/__fixtures__/ghosts.ts
 * ──────────────────────────────────────
 * Load the commit-able honest ghost and produce the canonical trajectory
 * tampers used by the re-simulation gate tests.
 *
 * Honest source: `honest-ghost.pcgh` / `honest-ghost.json`, generated by
 * `generate-honest-ghost.ts` from the pure sim core.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

import { decodeGhost, encodeGhost, type DecodedGhost } from "../../replay/codec";
import { resolveCourseOrThrow } from "./run";

const FIXTURE_DIR = path.join(process.cwd(), "lib/game/server/__fixtures__");

export interface HonestGhostFixture {
  ghost: DecodedGhost;
  bytes: Uint8Array;
  sampleHz: number;
  seed: number;
  course: ReturnType<typeof resolveCourseOrThrow>;
}

/** Decode the committed honest ghost (PCGH bytes on disk). */
export function loadHonestGhost(): HonestGhostFixture {
  const bytes = new Uint8Array(readFileSync(path.join(FIXTURE_DIR, "honest-ghost.pcgh")));
  const ghost = decodeGhost(bytes);
  const meta = JSON.parse(
    readFileSync(path.join(FIXTURE_DIR, "honest-ghost.json"), "utf8"),
  ) as { sampleHz: number; seed: number };
  return {
    ghost,
    bytes,
    sampleHz: meta.sampleHz,
    seed: meta.seed,
    course: resolveCourseOrThrow(),
  };
}

function reencode(ghost: DecodedGhost): DecodedGhost {
  const bytes = encodeGhost(ghost.samples, {
    physicsVersion: ghost.meta.physicsVersion,
    courseVersion: ghost.meta.courseVersion,
    sampleHz: ghost.meta.sampleHz,
    seed: ghost.meta.seed,
  });
  return decodeGhost(bytes);
}

/**
 * Time edit: keep only every 10th sample but preserve the original tick
 * indices. The ghost still claims the full elapsed span with far fewer
 * samples, so the average tick gap blows past the resim cadence check
 * (`duration_mismatch`). Consecutive re-tick would hide the edit.
 */
export function tamperDurationShrink(honest: DecodedGhost): DecodedGhost {
  const last = honest.samples.length - 1;
  const samples = honest.samples.filter((_, i) => i % 10 === 0 || i === last);
  return reencode({ meta: honest.meta, samples });
}

/** (2) Teleport — jump a mid-run sample by 600 m along Z. */
export function tamperTeleport(honest: DecodedGhost): DecodedGhost {
  const mid = Math.floor(honest.samples.length / 2);
  const samples = honest.samples.map((s, i) =>
    i === mid ? { ...s, zCm: s.zCm + 60_000 } : s,
  );
  return reencode({ meta: honest.meta, samples });
}

/** (3) Speed hack — spike a mid-run sample above MAX_RUN_SPEED_CMS. */
export function tamperSpeedHack(honest: DecodedGhost): DecodedGhost {
  const mid = Math.floor(honest.samples.length / 2);
  const samples = honest.samples.map((s, i) =>
    i === mid ? { ...s, speedCms: 15_000 } : s,
  );
  return reencode({ meta: honest.meta, samples });
}
