import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import { compareControls, residualSummary, auditResort } from './audit-terrain';
import { localProjection } from './dem/local-projection';
import { RESORT_BAKE_CONFIGS } from '../lib/game/terrain/resorts';

const center = [39.4749,-106.081] as const;
const projection = localProjection(center);
const datum = {verticalDatum:'NAVD88',verticalDatumVerified:true};
const input={slug:'breckenridge',horizontalCrs:'EPSG:4326',verticalDatum:'NAVD88',source:'Independent synthetic test survey',surveyDate:'2026-09-07',independentOfDem:true,toleranceM:.25,checkpoints:[{id:'A',lat:center[0],lon:center[1],elevationM:3000,uncertaintyM:.02}]};
test('checkpoint residuals report bias and error without fitting an offset',()=>{
 assert.deepEqual(residualSummary([-1,1]),{count:2,biasM:0,rmseM:1,p95AbsoluteM:1,maxAbsoluteM:1});
 const result=compareControls(input,'breckenridge',6144,projection,()=>3000.1,datum);
 assert.ok(result.withinTolerance);assert.ok(Math.abs(result.summary.biasM-.1)<1e-8);
 const shifted=compareControls(input,'breckenridge',6144,projection,()=>3001,datum);
 assert.equal(shifted.withinTolerance,false);assert.equal(shifted.summary.rmseM,1);
});
test('checkpoint validation fails closed on wrong datum, scope, malformed and duplicate inputs',()=>{
 assert.throws(()=>compareControls(input,'heavenly',6144,projection,()=>3000,datum),/resort mismatch/);
 assert.throws(()=>compareControls(input,'breckenridge',6144,projection,()=>3000,{...datum,verticalDatumVerified:false}),/datums/);
 assert.throws(()=>compareControls({...input,verticalDatum:'ellipsoid'},'breckenridge',6144,projection,()=>3000,datum),/datums/);
 assert.throws(()=>compareControls({...input,checkpoints:[{...input.checkpoints[0],lat:0}]},'breckenridge',6144,projection,()=>3000,datum),/outside/);
 assert.throws(()=>compareControls({...input,checkpoints:[input.checkpoints[0],input.checkpoints[0]]},'breckenridge',6144,projection,()=>3000,datum),/Duplicate/);
 for(const patch of [{checkpoints:[]},{toleranceM:Infinity},{independentOfDem:false},{surveyDate:'bad'}])assert.throws(()=>compareControls({...input,...patch},'breckenridge',6144,projection,()=>3000,datum));
 assert.throws(()=>residualSummary([NaN]),/Finite/);
});
test('checkpoint survey uncertainty is included in the acceptance bound',()=>{
 const result=compareControls({...input,checkpoints:[{...input.checkpoints[0],uncertaintyM:.3}]},'breckenridge',6144,projection,()=>3000,datum);
 assert.equal(result.withinTolerance,false);
});
// These are independent GDAL/PROJ outputs, not values generated by proj4js.
const probes=JSON.parse(fs.readFileSync('scripts/data/dem/projection-controls.json','utf8')) as {slug:string;lat:number;lon:number;eastingM:number;northingM:number}[];
for(const point of probes)test(`${point.slug} projected ${point.lat},${point.lon} agrees with GDAL within 1 mm`,()=>{
 const cfg=RESORT_BAKE_CONFIGS[point.slug],p=localProjection(cfg.center);
 const [x,y]=p.forward(point.lat,point.lon);
 assert.ok(Math.abs(x+p.origin[0]-point.eastingM)<.001);
 assert.ok(Math.abs(y+p.origin[1]-point.northingM)<.001);
 const [lat,lon]=p.inverse(x,y);
 assert.ok(Math.abs(lat-point.lat)<1e-9&&Math.abs(lon-point.lon)<1e-9);
});
for(const slug of ['breckenridge','heavenly','ski-portillo'] as const)test(`${slug} audit preserves every source sample and refuses a survey claim`,()=>{
 const report=auditResort(slug);
 assert.equal(report.sourceFidelity.identicalDecodedElevations,true);
 assert.equal(report.sourceFidelity.maxRuntimeOffsetM,0);
 assert.equal(report.accuracyStatus,'not-survey-certified');assert.equal(report.checkpoints,null);
 assert.ok(report.routes.length>0);assert.ok(report.routes.every(r=>r.dropM>0));
});
